# Generated by Django 5.1.3 on 2025-01-31 03:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('arrival_time', models.DateTimeField()),
                ('passengers_count', models.IntegerField(default=1, help_text="Number of passengers in owner's party", validators=[django.core.validators.MinValueValidator(1)])),
                ('vehicle_type', models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('van', 'Van'), ('luxury', 'Luxury')], max_length=10, null=True)),
                ('special_request', models.TextField(blank=True, null=True)),
                ('sharable', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CONFIRMED', 'Confirmed'), ('COMPLETE', 'Complete')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driven_rides', to='account.driver')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_rides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-arrival_time'],
            },
        ),
        migrations.CreateModel(
            name='RideShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengers', models.IntegerField(help_text="Number of passengers in sharer's party", validators=[django.core.validators.MinValueValidator(1)])),
                ('earliest_arrival', models.DateTimeField()),
                ('latest_arrival', models.DateTimeField()),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_shares', to='rides.ride')),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rideshare_set', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['status'], name='rides_ride_status_b1560e_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['destination'], name='rides_ride_destina_12f119_idx'),
        ),
        migrations.AddIndex(
            model_name='ride',
            index=models.Index(fields=['arrival_time'], name='rides_ride_arrival_a89fb5_idx'),
        ),
        migrations.AddIndex(
            model_name='rideshare',
            index=models.Index(fields=['ride', 'sharer'], name='rides_rides_ride_id_e17d9c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rideshare',
            unique_together={('ride', 'sharer')},
        ),
    ]
